name: Mr Coxall's Super Linter

on: [push, pull_request]

jobs:
  run-linters:
    name: Mr Coxall's Super Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository 🚦
        uses: actions/checkout@main

      - name: Run GitHub Super Linter 🚀
        uses: mr-coxall/super-linter@master
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_PYTHON_BLACK: true
          LINTER_RULES_PATH: /
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
